### PR TITLE
Eslint: lint js files and fix problems + gulp task for linting

### PR DESCRIPTION
**Pull request by abumalick**
* installed eslint for linting js
* config of eslint : [Airbnb JavaScript Style Guide(): ES5](https://github.com/airbnb/javascript/tree/es5-deprecated/es5)
* fixed linted stuff

**Warning : Don't merge into master before testing the changes !!**
The most breaking commit is [7a6a0823b35f52b0cb6f9c7af77260f77f57e9a0](https://github.com/miraath/mobile/commit/7a6a0823b35f52b0cb6f9c7af77260f77f57e9a0), please have a look at it because I couldn't test the changes I made !!

### CODE REVIEW

**Comment by Lahrachtdi** [comment]
Every thing looks good, but I will tested before merged in chaa allah

**Comment by Lahrachtdi** [comment]
I will fix the conflict after prayer in chaa allah

**Comment by abumalick** [comment]
I know, I modified miraath.js in sass-lint branch, and here for indentation.

**Comment by abumalick** [comment]
C'est bon inchaallah, j'ai fait un `git rebase master` pour mettre les commit de master avant ceux de cette branch.
On peut faire le merge sans conflits maintenant inchaallah
تفضل

**Comment by Lahrachtdi** [comment]
Assalamou allaykoum, a problem has accrued when I tried the test the app,  something is wrong with this file hooks\after_prepare\010_add_platform_class.js

**Comment by Lahrachtdi** [comment]
process.stdout.write accepte a string or a buffer as a parameter not an object and 'e' is an object.

**Comment by abumalick** [comment]
you can edit the file on your computer.
Then to update github with your change :
```bash
git checkout eslint
git add hooks
git status
git commit -m "010_add_platform_class.js: process.stdout.write accepte a string or a buffer as a parameter not an object and 'e' is an object."
git push origin eslint
```

**Comment by Lahrachtdi** [comment]
Ok, done.

**Pull request merged**
